# Generated by Django 5.1.4 on 2024-12-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_portable_portfolio_skills_delete_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='age',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
    ]
