# Generated by Django 5.1.4 on 2024-12-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='cv_pdf',
            field=models.FileField(blank=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True),
        ),
    ]
