# Generated by Django 5.1.4 on 2024-12-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_portfolio_about_me_portfolio_cv_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='about_me',
            field=models.TextField(blank=True, default='Default About Me'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='accent_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cv_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='github_link',
            field=models.URLField(blank=True, default='https://github.com'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='home_picture',
            field=models.ImageField(blank=True, null=True, upload_to='home_pictures/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='linkedin_link',
            field=models.URLField(default='https://www.linkedin.com'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='me_picture',
            field=models.ImageField(blank=True, null=True, upload_to='me_pictures/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='personal_quotes',
            field=models.CharField(default='Default Quote', max_length=250),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='role',
            field=models.CharField(default='Default Role', max_length=100),
        ),
    ]
